---
  name: ci
  
  on:
    workflow_dispatch:
      inputs:
        debug_enabled:
          type: boolean
          required: false
          default: false
  
    push:
      branches:
        - master
  
  jobs:
    build:
      runs-on: ubuntu-latest
      container: devkitpro/devkita64
  
      steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Build project
        run: make
  
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: SdOut/ovl-sysmodules.zip
