---
  name: release

  on:
    push:
      tags:
        - '*'

  jobs:
    release:
      uses: Lyaiya/github-workflow/.github/workflows/switch-release.yml@main
      with:
        file-path: SdOut/ovl-sysmodules.zip
